using MovieManagement.Models.DB_models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;


namespace MovieManagement.DAL
{
    public class MoviesInitializer : DropCreateDatabaseIfModelChanges<MoviesContext>
    {
        protected override void Seed(MoviesContext context)
        {
            // Seed the Genres table
            var genreSeedList = new List<Genres>();
            genreSeedList.Add(new Genres() { GenreId = 1, Name = "Comedy" });
            genreSeedList.Add(new Genres() { GenreId = 2, Name = "Action" });
            genreSeedList.Add(new Genres() { GenreId = 3, Name = "Horror" });
            genreSeedList.Add(new Genres() { GenreId = 4, Name = "Sci-Fi" });
            genreSeedList.Add(new Genres() { GenreId = 5, Name = "Romance" });

            // Save the values to the DB to ensure Id's are generated
            context.Genres.AddRange(genreSeedList);


            //// Get the saved genre's with their autogenerated Id's
            //var genres = context.Genres.ToList();

            // Add movies with genre's (linking Id's from the 'genres' list)
            // There is probably a cleaner way of doing this, but my code first is pretty rusty. I beg forgiveness
            // I will get better. Fast :D
            var moviesSeedList = new List<Movies>();
            moviesSeedList.Add(new Movies()
            {
                Title = "Inception",
                Genres = new List<Genres>() { genreSeedList.Where(g => g.GenreId == 2).FirstOrDefault() },
                Released = new DateTime(2010, 7, 16)
            });
            moviesSeedList.Add(new Movies()
            {
                Title = "Mad Max - Fury road",
                Genres = new List<Genres>() {  genreSeedList.Where(g => g.GenreId == 2).FirstOrDefault(),
                                                genreSeedList.Where(g => g.GenreId == 3).FirstOrDefault()
                                              },
                Released = new DateTime(2015, 5, 7)
            });
            moviesSeedList.Add(new Movies()
            {
                Title = "Deadpool",
                Genres = new List<Genres>() {  genreSeedList.Where(g => g.GenreId == 2).FirstOrDefault(),
                                               genreSeedList.Where(g => g.GenreId == 1).FirstOrDefault(),
                                               genreSeedList.Where(g => g.GenreId == 5).FirstOrDefault()
                                              },
                Released = new DateTime(2010, 7, 16)
            });


            // Save the newly added movies
            context.Movies.AddRange(moviesSeedList);


            base.Seed(context);
        }
    }
}